apiVersion: skaffold/v2beta3
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ovist/section14-client
      context: ./client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
        - src: '**/*.js'
          dest: .
        - src: '**/*.css'
          dest: .
        - src: '**/*.html'
          dest: .
deploy:
  kubectl:
    manifests:
      - k8s/client-deployment.yaml
